"""
handlers/link.py  —  /link command

Permanent link architecture (FileStreamBot-style):
  1. User replies to any file with /link
  2. Bot forwards file to DUMP_CHANNEL (permanent storage)
  3. File metadata stored in MongoDB link_files collection
  4. Permanent URL generated: {STREAM_BASE_URL}/watch/{mongo_id}
  5. Links never expire — tied to the DUMP_CHANNEL message

UI (matches screenshot):
  ➛ File Name : filename.mp4
  ➛ File Size : 59.81 MiB
  ➛ Download  : https://...
  ➛ Watch Online : https://...
  Note :- Use IDM (For PC) or 1DM (For Mobile) To Download With Maximum Speed
  ⭐ Generated By @BotName

  [Watch Online]  [Download]
"""

from mimetypes import guess_type

from pyrogram import Client, filters
from pyrogram.enums import ParseMode
from pyrogram.types import (
    Message, InlineKeyboardMarkup, InlineKeyboardButton,
)

import database as db
import pyrogram_helper as pyro
from config import BOT_TOKEN, BOT_USERNAME, STREAM_BASE_URL, DUMP_CHANNEL
from logger import log_action

MD = ParseMode.MARKDOWN


def _full_name(u) -> str:
    parts = [u.first_name or "", u.last_name or ""]
    return " ".join(p for p in parts if p).strip() or "Unknown"


def _human_size(n: int) -> str:
    for unit in ("B", "KiB", "MiB", "GiB"):
        if n < 1024:
            return f"{n:.2f} {unit}"
        n /= 1024
    return f"{n:.2f} TiB"


def _is_public_url(url: str) -> bool:
    if not url:
        return False
    private = ("localhost", "127.", "192.168.", "10.", "172.16.", "0.0.0.0")
    return not any(p in url.lower() for p in private)


def register(app: Client):

    @app.on_message(filters.command("link") & filters.private)
    async def cmd_link(client: Client, message: Message):
        u = message.from_user
        await db.ensure_user(u.id, u.username, _full_name(u))

        r = message.reply_to_message
        if not r:
            await message.reply(
                "↩️ **How to use /link**\n\n"
                "Reply to any **video**, **document**, or **audio** with `/link`\n"
                "to get a **permanent** Watch Online + Download link.\n\n"
                "📌 _Links never expire._",
                parse_mode=MD,
            )
            return

        # ── Identify media ─────────────────────────────────────────────────────
        media_obj  = None
        file_name  = "file"
        file_size  = 0
        mime_type  = "application/octet-stream"
        file_id    = ""
        file_uid   = ""

        if r.video:
            media_obj = r.video
            file_name = r.video.file_name or "video.mp4"
            file_size = r.video.file_size or 0
            mime_type = r.video.mime_type or "video/mp4"
            file_id   = r.video.file_id
            file_uid  = r.video.file_unique_id
        elif r.document:
            media_obj = r.document
            file_name = r.document.file_name or "file"
            file_size = r.document.file_size or 0
            mime_type = (r.document.mime_type
                         or guess_type(r.document.file_name or "")[0]
                         or "application/octet-stream")
            file_id   = r.document.file_id
            file_uid  = r.document.file_unique_id
        elif r.audio:
            media_obj = r.audio
            file_name = r.audio.file_name or "audio.mp3"
            file_size = r.audio.file_size or 0
            mime_type = r.audio.mime_type or "audio/mpeg"
            file_id   = r.audio.file_id
            file_uid  = r.audio.file_unique_id

        if not media_obj:
            await message.reply(
                "❌ Please reply to a **video**, **document**, or **audio** file.",
                parse_mode=MD,
            )
            return

        if not STREAM_BASE_URL or not _is_public_url(STREAM_BASE_URL):
            await message.reply(
                "⚠️ `STREAM_BASE_URL` is not set or is a private address.\n"
                "Set a public URL in your `.env` to enable /link.",
                parse_mode=MD,
            )
            return

        if not DUMP_CHANNEL:
            await message.reply(
                "⚠️ `DUMP_CHANNEL` is not configured.\n"
                "Set a channel ID in your `.env` where the bot is admin.",
                parse_mode=MD,
            )
            return

        wait = await message.reply("⏳ Generating permanent link…")

        try:
            # ── Forward to DUMP_CHANNEL for permanent storage ──────────────────
            dump_msg = await client.forward_messages(
                chat_id    = DUMP_CHANNEL,
                from_chat_id = message.chat.id,
                message_ids  = r.id,
            )
            dump_msg_id = dump_msg.id

            # Get the actual file_id from the dump message (for streaming)
            dump_media = (
                dump_msg.video or dump_msg.document or dump_msg.audio
            )
            stream_file_id = getattr(dump_media, "file_id", file_id) if dump_media else file_id

            # ── Store in MongoDB ───────────────────────────────────────────────
            mongo_id = await db.add_link_file(
                tg_file_id        = stream_file_id,
                tg_file_unique_id = file_uid,
                file_name         = file_name,
                file_size         = file_size,
                mime_type         = mime_type,
                dump_msg_id       = dump_msg_id,
            )

        except Exception as e:
            await wait.edit(
                f"❌ Failed to store file:\n`{e}`\n\n"
                "Make sure the bot is **admin** in `DUMP_CHANNEL`.",
                parse_mode=MD,
            )
            return

        # ── Build permanent URLs ───────────────────────────────────────────────
        base       = STREAM_BASE_URL.rstrip("/")
        watch_url  = f"{base}/watch/{mongo_id}"
        dl_url     = f"{base}/dl/{mongo_id}"
        size_str   = _human_size(file_size)

        text = (
            f"➛ **File Name** : `{file_name}`\n"
            f"➛ **File Size** : `{size_str}`\n\n"
            f"➛ **Download** : {dl_url}\n\n"
            f"➛ **Watch Online** : {watch_url}\n\n"
            f"**Note :-** _Use IDM (For PC) or 1DM (For Mobile) To Download With Maximum Speed_\n\n"
            f"⭐ **Generated By** @{BOT_USERNAME}"
        )

        buttons = [[
            InlineKeyboardButton("▶️ Watch Online", url=watch_url),
            InlineKeyboardButton("⬇️ Download",     url=dl_url),
        ]]

        await wait.delete()
        await message.reply(
            text,
            parse_mode=MD,
            reply_markup=InlineKeyboardMarkup(buttons),
            disable_web_page_preview=True,
        )

        # ── Log to LOG_CHANNEL ─────────────────────────────────────────────────
        await log_action(client, message, "🔗 Link Generated", f"`{file_name}` ({size_str})")
